inherit: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
    - src/*

build:
    environment:
        php: '5.6.16'
    tests:
        override:
            -
                command: ./vendor/phpunit/phpunit/phpunit
                coverage:
                    file: ./build/phpunit/clover.xml
                    format: php-clover
